### ISSUE TITLE
Misspelling/Typo

### ISSUE THREAD

**Issue by MackRoe** [Make-School-Courses/SPD-2.31-Testing-and-Architecture#4]
Line 5
`    print("saved into databse")`
should be
`    print("Saved into database.")

**Comment by NinjaAung** [comment]
Make sure you refrence the line you are talking about!  like this:

https://github.com/Make-School-Courses/SPD-2.31-Testing-and-Architecture/blob/d6e46a6784b6ffe25cbcf9e349801d4c720ba1de/lab/refactoring/split_temp_variable2.py#L1-L5

Thank you for mentioning it
